### PR TITLE
Consistent logging, set parameters, maven central preparation

### LINKED ISSUE #11: CPLEX Default Time Limit of 10 minutes
If you use the XOR Winner Determination in a big auction. (eg. LSVM Standard Configuration with all 6 * 2^16 bids), then it is possible that the winner determination reports missleading results.

CPLEX has by default a time limit of 10 minutes. Whenever it wasn't possible to find the optimal solution within 10 minutes, CPLEX just reports the best feasible solution it found so far. Because this happens without a notifcation, a user could assume that this is the optimal solution even though it is not.

In my opinion the user should have the opportunity to increase this time limit and if the winner determination truly stops because of this time limit then there should be an exception by default. 
Because I cannot really see the use case where a user would like to continue with a suboptimal solution in a winner determination problem.

With the following solve param, the default time limit of 600 seconds can be changed:

`mip.setSolveParam(SolveParam.TIME_LIMIT, 7200.0);`

### LINKED ISSUE #15: Consistently implement logging
Using log4j2, have a clean logging in place

### PR DESCRIPTION
**Pull request by islerfab**
Resolves #11 and resolves #15.
* First purpose: Replaced all System.out.println with log4j2 logging
* Changes that evolved while working on the logging:
  * Added a superclass for the model's MIPs to easily set the most relevant parameters (TIME_LIMIT, ACCEPT_SUBOPTIMAL, DISPLAY_OUTPUT)
  * Prepared pom.xml and fixed javadoc errors for a release on Maven Central
  * Minor cleanup here and then

### CODE REVIEW

File: src/main/java/org/spectrumauctions/sats/opt/model/mrvm/MRVMWorldPartialMip.java [hunk 1]
```diff
@@ -7,6 +7,8 @@
 
 import com.google.common.base.Preconditions;
 import edu.harvard.econcs.jopt.solver.mip.*;
+import org.apache.logging.log4j.LogManager;
```
Comment (MiWeiss) [inline src/main/java/org/spectrumauctions/sats/opt/model/mrvm/MRVMWorldPartialMip.java:10]: yes :-) finally... sysos are gone :-D

**Review by MiWeiss — APPROVED** [review]
Thanks! :-)
